### ISSUE TITLE
Form field not found

### ISSUE THREAD

**Issue by bartonhammond** [dzschille/behat3-cbt#1]
I did `composer install` and updated the `behat.yml` with my user/key and then ran `bin/behat` and got this failure:

Also, I see no evidence this made to CBT - there's no History of this running on CBT.

<img width="1025" alt="screen shot 2018-05-17 at 8 18 35 am" src="https://user-images.githubusercontent.com/1282364/40179918-15c72bd6-59ab-11e8-9b4f-4cfb3e654f13.png">

**Comment by dzschille** [comment]
You must urlencode your username: the "@" is encoded: "%40".
And did you uncommented the line with the crossbrowsertesting.com/wd/hub?

**Comment by dzschille** [comment]
I just tested it after a fresh `composer update`. It still runs fine here.

**Comment by bartonhammond** [comment]
Yes - I saw that in the read me.

I tried this:

```   
wd_host:ttps://barton%40wisnet.com:u0450%40crossbrowsertesting.com/wd/hub
```

and tried this:
```
wd_host:ttps://barton%40wisnet.com:u0450@crossbrowsertesting.com/wd/hub
```

**Comment by dzschille** [comment]
You missed an space an the "h" before "ttps://barton..."

**Comment by bartonhammond** [comment]
Ok - got it.   I must have copied my key wrong.  

Thanks!

**Comment by dzschille** [comment]
That's great! Have fun!
